- id: '1563036110982'
  alias: Node-Red-Watchdog
  trigger:
  - entity_id: sensor.node_red
    from: OK
    platform: state
    to: Unknown
  condition: []
  action:
  - data:
      addon: a0d7b954_nodered
    service: hassio.addon_restart
  - alias: ''
    data:
      data:
        message: Node-Red has been restarted
        title: Node-Red Restarted
    service: notify.notify
- id: '1583376478710'
  alias: Set theme on startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: midnight
    service: frontend.set_theme
