- id: '1563036110982'
  alias: Node-Red-Watchdog
  trigger:
  - entity_id: sensor.node_red
    from: OK
    platform: state
    to: Unknown
  condition: []
  action:
  - data:
      addon: a0d7b954_nodered
    service: hassio.addon_restart
  - alias: ''
    data:
      data:
        message: Node-Red has been restarted
        title: Node-Red Restarted
    service: notify.notify
- id: '1583376478710'
  alias: Set theme on startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: midnight
    service: frontend.set_theme
- id: '1608570018261'
  alias: Zone Notification - CJ(Home)
  description: ''
  use_blueprint:
    path: homeassistant/notify_leaving_zone.yaml
    input:
      person_entity: person.cj
      zone_entity: zone.home
      notify_device: 558415e5e7c72600216e661fdf07b0ad
