#  - platform: ffmpeg
#    input: !secret camera_front
#    name: Front Door
- platform: ffmpeg
  input: !secret camera_side
  name: Side Door
- platform: ffmpeg
  input: !secret camera_deckn
  name: Deck North
- platform: ffmpeg
  input: !secret camera_decks
  name: Deck South
- platform: ffmpeg
  input: !secret camera_north
  name: North Side
- platform: ffmpeg
  input: !secret camera_sump
  name: Sump Pump
