homeassistant:
    customize: !include customize.yaml
    packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

cloud:

http:
    ip_ban_enabled: true
    login_attempts_threshold: 10

# Text to speech
tts:
  - platform: google_translate

device_tracker:
  - platform: google_maps
    username: !secret presence_user

google:
    client_id: !secret google_cal_clientid_prod
    client_secret: !secret google_cal_clientsecret_prod

badnest:
  issue_token: !secret badnest_token
  cookie: !secret badnest_cookie
  region: us

climate:
  platform: badnest
  scan_interval: 10

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor: !include sensors.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
camera: !include cameras.yaml
group: !include groups.yaml
