esphome:
  name: esphome-doorbell
  friendly_name: Doorbell

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "2czD/ekhFaM2q5aZl0wAp4tyjrgwtx+L9Whfsa4QoM0="

ota:
  password: "1a9138ef9079400f24d240f44914af44"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Doorbell"
    password: "IqfOVoa7U4cD"

captive_portal:

# Enable Web server.
web_server:
  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Doorbell ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Doorbell IP
    ssid:
      name: Doorbell SSID
    bssid:
      name: Doorbell BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Doorbell Uptime
    filters:
      - lambda: return (x/60);
    unit_of_measurement: "Min"
  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Doorbell WiFi Signal
    update_interval: 60s

# Exposed switches.
switch:
  # Switch to restart the front doorbell.
  - platform: restart
    name: Doorbell Restart

binary_sensor:
  - platform: gpio
    pin:
      number: D1
      mode: INPUT_PULLUP
    name: "Front Door"
    device_class: motion
    filters:
      - delayed_on: 5ms
  - platform: gpio
    pin: 
      number: D2
      mode: INPUT_PULLUP
    name: "Side Door"
    device_class: motion
    filters:
      - delayed_on: 5ms