esphome:
  name: master-multisensor
  friendly_name: master_multisensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "eJqQsZ1Z5Aig6oLXsSknVpSLNjTlqGWT9aWS0Q/iklA="

ota:
  password: "8c68f7882e712542e19f2e4c30eb1946"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master-Multisensor"
    password: "Af8ADl33vnrk"

captive_portal:

sensor:
  - platform: dht
    pin: D7
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"

binary_sensor:
  - platform: gpio
    pin: D5
    name: "Multisensor Motion"
    device_class: motion
