esphome:
  name: opensprinkler
  libraries:
    - ShiftRegister74HC595@1.2

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "7DhWKi3uJBfcu7a1IKPxV0Vhx0EUEXZ5PdB7GQIJzgM="

ota:
  password: "af561f01f5558b986bb1bbf8f1c0f04a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Opensprinkler Fallback Hotspot"
    password: "M0n0l1th1c$$"

captive_portal:

switch:
  - platform: gpio
    name: "Zone 1"
    pin: D1
  - platform: gpio
    name: "Zone 2"
    pin: D2
  - platform: gpio
    name: "Zone 3"
    pin: D3
  - platform: gpio
    name: "Zone 4"
    pin: D4
  - platform: gpio
    name: "Zone 5"
    pin: D5
  - platform: gpio
    name: "Zone 6"
    pin: D6
  - platform: gpio
    name: "Zone 7"
    pin: D7
  - platform: gpio
    name: "Zone 8"
    pin: D8

status_led:
    pin: 16

text_sensor:
  - platform: version
    name: esphome_sprinkler_system_esphome_version
